// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa4TOpSMvrZI4a0n6e1VqjORQzif9Pck8',
    appId: '1:1073271165345:web:faacccadbb5fc6b8cdfbe0',
    messagingSenderId: '1073271165345',
    projectId: 'arihant-bike-scooty-spare',
    authDomain: 'arihant-bike-scooty-spare.firebaseapp.com',
    storageBucket: 'arihant-bike-scooty-spare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhR2nAGGD7Nl2XKUR78ISraHP5_A89ziQ',
    appId: '1:1073271165345:android:4d99714ca0c05698cdfbe0',
    messagingSenderId: '1073271165345',
    projectId: 'arihant-bike-scooty-spare',
    storageBucket: 'arihant-bike-scooty-spare.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDHMi6-_2blD_YL-m07uvy0YNyr2BZh70',
    appId: '1:1073271165345:ios:5f4ccb46a5db0850cdfbe0',
    messagingSenderId: '1073271165345',
    projectId: 'arihant-bike-scooty-spare',
    storageBucket: 'arihant-bike-scooty-spare.firebasestorage.app',
    iosBundleId: 'com.example.spareApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDHMi6-_2blD_YL-m07uvy0YNyr2BZh70',
    appId: '1:1073271165345:ios:5f4ccb46a5db0850cdfbe0',
    messagingSenderId: '1073271165345',
    projectId: 'arihant-bike-scooty-spare',
    storageBucket: 'arihant-bike-scooty-spare.firebasestorage.app',
    iosBundleId: 'com.example.spareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa4TOpSMvrZI4a0n6e1VqjORQzif9Pck8',
    appId: '1:1073271165345:web:699c1060b252f565cdfbe0',
    messagingSenderId: '1073271165345',
    projectId: 'arihant-bike-scooty-spare',
    authDomain: 'arihant-bike-scooty-spare.firebaseapp.com',
    storageBucket: 'arihant-bike-scooty-spare.firebasestorage.app',
  );
}
